lab_9/urls.py
from django.urls import re_path, path
from django.conf.urls import url
from .views import *

app_name = 'lab_9'

urlpatterns = [
    path('landingPage', index, name='index'),
    path('json', json, name='json'),
    path('formRegister/', formRegister, name='formRegister'),
    path('email-check/', check_email, name='check_email'),
    path('subscribe/', subscribe, name='subscribe'),


]

ppwreponew/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from lab_9.views import *

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path('', include('lab_9.urls')),
    re_path(r'^$', index, name='index'),
]

lab_9/models.py
from django.db import models

class FormRegisterModels(models.Model):
	nama = models.CharField(max_length=30)
	email = models.EmailField(unique=True)
	password = models.CharField(max_length=30)
# Create your models here.

lab_9/forms.py
from django import forms
from .models import FormRegisterModels
class FormRegister(forms.Form):
    attrs = {
        'class': 'form-control'
    }

    nama = forms.CharField(label = 'Nama Lengkap', required=True, widget=forms.TextInput(attrs=attrs), max_length=30)
    email = forms.EmailField(label = 'Email', required=True, widget=forms.EmailInput(attrs=attrs), max_length=30)
    password = forms.CharField(label = 'Password', required=True, widget=forms.PasswordInput(attrs=attrs), max_length=15)
    class Meta:
    	model = FormRegisterModels
    

lab_9/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import *
from .models import *

response = {}

def index(request):
	return render(request, 'landingPage.html', {})

def json(request, category=''):
    apis = requests.get(url="https://www.googleapis.com/books/v1/volumes?q="+{category})
    data = apis.json()
    return JsonResponse(data)


def daftar_buku(request):
    return render(request, 'landingPage.html')

def formRegister(request):
    response = {'form_daftar' : FormRegister}
    return render(request, 'formRegister.html', response)

@csrf_exempt
def check_email(request):
    email = request.POST['email']
    db = FormRegisterModels.objects.all()
    terdaftar = 'Email sudah pernah terdaftar'
    for data in db:
        if email == data.email:
            return JsonResponse({'message': terdaftar})
    return JsonResponse({'message': 'Ok'})

@csrf_exempt
def subscribe(request):
    nama = request.POST['nama']
    email = request.POST['email']
    password = request.POST['password']
    FormRegisterModels(nama=nama, email=email, password=password).save()
    return JsonResponse({'message': 'Anda telah terdaftar'})



	
	




# Create your views here.

lab_9/templates/footer.html
<html>
	<footer>
	    <br>
	    <p>Yudha Pradipta Ramadan</p>
	    <p>1706043424</p>
	</footer>
</html>

lab_9/templates/formRegister.html
{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% csrf_token %}
    <!--{% load staticfiles %}-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Form Registrasi</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href ="{% static 'css/style.css' %}">
  </head>
    <section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST">
            {% csrf_token %}
            {{form_daftar}}
        <br>
        </form>
        <div class='text-center'><button class='btn btn-success' disabled id='id_button'>Submit</button></div>
    </div>
</section>

    <script type="text/javascript">
    $('<p id="info_email" class="text-right"><b></b></p>').insertAfter('#id_email');
    $('<p></p>').insertAfter('#id_nama');

    $('#id_email').change(function() {
                $.ajax({
                    method: "POST",
                    url : '/email-check/',
                    data: { email: $('#id_email').val()},
                    success: function(msg) {
                        $('#info_email b').html(msg.message);
                }
            });
        });
    
    function allValid(){
        var valid = true;
        $('body input').each(function() {
            if($(this).val() == '' || $('#info_email b').html() != 'Ok'){
                 valid = false;
            }
        });
        return valid;
    }
    
    $('#id_nama, #id_email, #id_password').bind('keyup', function() {
        if (allValid()){
            $("#id_button").removeAttr('disabled');
        }else{
            $("#id_button").attr('disabled', 'true');
        }
    });
    
    $('#id_button').click(function() {
            $.ajax({
                method: 'POST',
                url: '/subscribe/',
                data: { nama: $("#id_nama").val(),
                        email: $("#id_email").val(),
                        password: $("#id_password").val()
                },
                success: function(msg) {
                    $("#id_nama").val('');
                    $("#id_email").val('');
                    $("#id_password").val('');
                    $('#info_email b').html('');
                    alert(msg.message);
                }
            })
        });


</script>




</html>
{% endblock %}

lab_9/templates/landingPage.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Yudha's Libary</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href ="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
    <script>
        var favCount=0;
        function fav(id){
          var ids= $('#' +id);
          if (ids[0].src == 'https://i.postimg.cc/3rjJgKZY/valentines-heart.png') {
                favCount--;
                ids[0].src = 'https://i.postimg.cc/hv8jvn24/e-commerce-like-heart-1.png';
            } else {
                favCount++;
                ids[0].src = 'https://i.postimg.cc/3rjJgKZY/valentines-heart.png';
            }
            $('#counter').html('<br>'+'<p>Favorite Books : '+ favCount + '</p>');
        }
        function pilihKategori(category){
          $('#counter').html('<br><p>Favorite Books : '+ favCount+ '</p>');
          $('#books').html("<tr><th id='table'>Cover</th><th id='table'>Title</th><th id='table'>Author</th><th> Fav </th></tr>")
          $.ajax({
            url: 'https://www.googleapis.com/books/v1/volumes?q='+category,
            success: function(obj){
              var i;
              for(i=0; i<obj.items.length; i++){
                var judul= obj.items[i]['volumeInfo']['title'];
                var image= '<img src="' + obj.items[i]['volumeInfo']['imageLinks']['thumbnail'] +'">';
                var author= obj.items[i]['volumeInfo']['authors'];
                $('#books').append('<tr><td>'+image+'</td><td>'+judul+'</td><td>'+ author+'</td><td><img style="cursor:pointer;" height="40" width="40" onclick=fav("'+ obj.items[i].id +'") id='+obj.items[i].id+ ' src="https://i.postimg.cc/hv8jvn24/e-commerce-like-heart-1.png" style="height:50px;"></td></tr>');
                }
              }
          })
        }
    </script>
  </head>

  <br>

  <body>
      <div class="container">
        <h1 id=welcome style="text-align: center;">Welcome to my Library</h1>
        <br>
        <p>Untuk mencari, tombol search harus dipencet</p>
        <p>Search pertama akan terhapus bila mengganti isi dari search bar dan memencet tombol search lagi</p>
        <div id="counter">
          <br>
          <p>Favorite Books : </p>
        </div>
        Search Bar : <input type="text" id="myText" value="">  <button onclick="pilihKategori(myText.value)">Search</button>
        <br>
        <br>
      </div>

      <table id= 'books' class="table table-responsive container" style="text-align: center;background-color:rgb(255,255,255,0.5)">
      <tr>
        <th id='table'>Cover</th>
        <th id='table'>Title</th>
        <th id='table'>Author</th>
        <th> Fav </th>
      </tr>
      </table>
  </body>
  <footer>
    <br>
    <p>Yudha Pradipta Ramadan</p>
    <p>1706043424</p>
  </footer>
</html>

{% block content %}
{% endblock %}